APP_VERSION = "1.5.2-fork.1"
UPDATE_CHANNEL = "release"
REPOSITORY_URL = "https://github.com/HorryTsui/OverwatchDropsMiner"
LATEST_RELEASE_API = "https://api.github.com/repos/HorryTsui/OverwatchDropsMiner/releases/latest"
RELEASES_URL = "https://github.com/HorryTsui/OverwatchDropsMiner/releases/latest"
